AWSTemplateFormatVersion: 2010-09-09
Description: VPC for data lake as a service - core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: hamsa
  Environment:
     Type: String
     Default: dev
     AllowedValues: [dev, tst, int, uat, prd, poc]

Resources:
  CreateVPCForDaaS:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub ${Entity}-vpc-daas-core-${Environment}
        PrivateSubnet1Cidr: 10.1.0.0/24
        PrivateSubnet2Cidr: 10.1.16.0/24
        PrivateSubnet1AZ: us-east-1d
        PrivateSubnet2AZ: us-east-1c
        PublicSubnet1Cidr: 10.1.129.0/24
        PublicSubnet2Cidr: 10.1.145.0/24
        PublicSubnet1AZ: us-east-1a
        PublicSubnet2AZ: us-east-1b
        VpcCidrBlock: 10.1.0.0/16
      TemplateURL: !Sub https://${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-dev.s3.amazonaws.com/vpc/scripts/template/cft-vpc-common-template.yml
      TimeoutInMinutes: '60'
