AWSTemplateFormatVersion: 2010-09-09
Description: NAT Gateway for data lake as a service - client (DaaS - Client)

Parameters:
  Entity:
    Type: String
    Default: hamsa
  Environment:
     Type: String
     Default: dev
     AllowedValues: [dev, tst, int, uat, prd, poc]

Resources:
  CreateNGWForDaaSCore:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Environment: !Ref Environment
        Name: !Sub '${Entity}-ngw-daas-client-${Environment}'
      #TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/ngw/scripts/template/cft-ngw-common-template.yml
      TimeoutInMinutes: '60'
      TemplateURL: https://hamsa-s3-902380713093-us-east-1-common-artifacts-dev.s3.amazonaws.com/ngw/scripts/template/cft-ngw-common-template.yml