AWSTemplateFormatVersion: 2010-09-09
Description: Test Raw bucket for data lake as a service - client (DaaS - Client)

# Required Parameters: Environment
Parameters:
  Entity:
    Type: String
    Default: hamsa
  Environment:
    Type: String
    Default: dev

# Create Resources
Resources:
  CreateDaaSRawBucket:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Environment: !Sub ${Environment}
        Name: !Sub ${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket
      #TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/s3/scripts/template/cft-s3-common-template.yml
      TimeoutInMinutes: '60'
      TemplateURL: https://hamsa-s3-902380713093-us-east-1-common-artifacts-dev.s3.amazonaws.com/s3/scripts/template/cft-s3-common-template.yml

  CreateDaaSRawBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: CreateDaaSRawBucket
    Properties:
      Bucket: !Sub ${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket-${Environment}
      PolicyDocument:
        Statement:
          - Sid: Allow DaaS Core Role access
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:PutBucketPolicy"
            Resource:
              - !Sub arn:aws:s3:::${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket-${Environment}
              - !Sub arn:aws:s3:::${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket-${Environment}/*
          - Sid: Deny insecure access
            Effect: Deny
            Principal: "*"
            Action: "*"
            Resource:
              - !Sub arn:aws:s3:::${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket-${Environment}
              - !Sub arn:aws:s3:::${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket-${Environment}/*
            Condition:
              Bool:
                "aws:SecureTransport": false
